version: "3"
services:
  nginx:
    image: nginx
  eureka:
    build: ../spring-cloud/eureka
  zuul:
    build: ../spring-boot/service-zuul
  feign:
    build: ../spring-boot/service-feigin
  hi:
    build: ../spring-boot/service-hi
  mysql:
    image: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: qw12
  redis: 
    image: redis
  minio:
    image: minio
  pgsql:
    image: postgres
    volumes:
     - pgsql_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: qw12
  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db
    restart: always
  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - "8089:8081"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
     - "8090:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: qw12
volumes:
  mysql_data:
  redis_data:
  minio_data:
  pgsql_data:
  mongo_data: